name = "cloudflare-hono-lucia-auth"
compatibility_date = "2024-09-10"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "lucia-email-and-password"
database_id = "10119f7d-ab3c-4c1d-b46d-f0718e2fbea7"

routes = [
  { pattern = "https://www.e-ayala.com/", custom_domain = true }
]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"